extends: 'eslint:recommended'
env:
  worker: true
  browser: true
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-cond-assign:
    - off
  no-trailing-spaces:
    - error
overrides:
  - files: '**/*.test.js'
    env:
      mocha: true
