name: coverage
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git clone --branch=gh-pages --depth=1 "https://za-creature:${{ github.token }}@github.com/${{ github.repository }}.git" coverage/
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-
    - run: npm install
    - run: npm run cover
    - run: git config --global user.email "no-reply.actions.cf-emu.za-creature@github.com"
    - run: git config --global user.name "GitHub Actions"
    - run: cd coverage && git add . && git commit -m 'Update coverage' && git push
